apiVersion: v1
kind: Pod
metadata:
  name: title-classer-pod
  labels:
    bb: web

spec:
  containers:
  - image: dandovhun/title_classer
    name: title-classer-pod
  restartPolicy: Always
  imagePullSecrets:
     - name: app-secret

